#include "ast.h"
#include <stdlib.h>
#include <stdio.h>

Node* create(int type, int ival, Node *back, Node *left, Node *right, Node *forth)
{
    Node *N = (Node*)malloc(sizeof(Node));

    N->type  = type ;
    N->ival  = ival ;
    N->left  = left ;
    N->right = right;
    N->back  = back ;
    N->forth = forth;

    return N;
}

void xuxa(Node *N)
{
    switch (N->type)
    {
        case  0: printf("prog prog_elements -> prog\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case  1: printf("PRNAME ID -> direct\n");
                 break;
        case  2: printf("DIRNAM STRING -> direct\n");
                 break;
        case  3: printf("DATYPE INUM -> direct\n");
                 break;
        case  4: printf("NUBITS INUM -> direct\n");
                 break;
        case  5: printf("NBMANT INUM -> direct\n");
                 break;
        case  6: printf("NBEXPO INUM -> direct\n");
                 break;
        case  7: printf("NDSTAC INUM -> direct\n");
                 break;
        case  8: printf("SDEPTH INUM -> direct\n");
                 break;
        case  9: printf("NUIOIN INUM -> direct\n");
                 break;
        case 10: printf("NUIOOU INUM -> direct\n");
                 break;
        case 11: printf("NUGAIN INUM -> direct\n");
                 break;
        case 12: printf("FFTSIZ INUM -> direct\n");
                 break;
        case 13: printf("ID -> IID\n");
                 break;
        case 14: printf("TYPE id_list ';' -> declar\n");
                 xuxa(N->right);
                 break;
        case 15: printf("id_list ',' IID -> id_list\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 16: printf("ID '[' INUM ']' -> IID\n");
                 break;
        case 17: printf("ID '[' INUM ']' '[' INUM ']' -> IID\n");
                 break;
        case 18: printf("TYPE ID '[' INUM ']' STRING ';' -> declar\n");
                 break;
        case 19: printf("TYPE ID '[' INUM ']' '[' INUM ']' STRING ';' -> declar\n");
                 break;
        case 20: printf("TYPE ID '(' ')' '{' stmt_list '}'-> funcao\n");
                 xuxa(N->right);
                 break;
        case 21: printf("BREAK ';' -> wbreak\n");
                 break;
        case 22: printf("TYPE ID -> par_list\n");
                 break;
        case 23: printf("TYPE ID '(' par_list ')' '{' stmt_list '}' -> funcao\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 24: printf("par_list ',' par_list -> par_list\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 25: printf("stmt_list stmt -> stmt_list\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 26: printf("INUM -> exp\n");
                 break;
        case 27: printf("FNUM -> exp\n");
                 break;
        case 28: printf("ID -> exp\n");
                 break;
        case 29: printf("ID '[' exp ']' -> exp\n");
                 xuxa(N->right);
                 break;
        case 30: printf("ID '[' exp '|' -> exp\n");
                 xuxa(N->right);
                 break;
        case 31: printf("ID '[' exp ']' '[' exp ']' -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 32: printf("ID '=' exp ';' -> assignment\n");
                 xuxa(N->right);
                 break;
        case 33: printf("ID '@' exp ';' -> assignment\n");
                 xuxa(N->right);
                 break;
        case 34: printf("ID NORM exp ';' -> assignment\n");
                 xuxa(N->right);
                 break;
        case 35: printf("ID '$' exp ';' -> assignment\n");
                 xuxa(N->right);
                 break;
        case 36: printf("ID EQNE exp ';' -> assignment\n");
                 xuxa(N->right);
                 break;
        case 37: printf("ID '(' exp_list ')' -> func_call\n");
                 xuxa(N->right);
                 break;
        case 38: printf("exp -> exp_list\n");
                 xuxa(N->left);
                 break;
        case 39: printf("exp_list ',' exp -> exp_list\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 40: printf("vazio -> exp_list\n");
                 break;
        case 41: printf("RETURN exp ';' -> return_call\n");
                 xuxa(N->right);
                 break;
        case 42: printf("'-' exp -> exp\n");
                 xuxa(N->right);
                 break;
        case 43: printf("OUT '(' exp ',' exp ')' ';' -> std_out\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 44: printf("IN '(' exp ')' -> std_in\n");
                 xuxa(N->right);
                 break;
        case 45: printf("PST '(' exp ')' -> std_pst\n");
                 xuxa(N->right);
                 break;
        case 46: printf("ABS  '(' exp ')' -> std_abs\n");
                 xuxa(N->right);
                 break;
        case 47: printf("SIGN '(' exp ',' exp ')' -> std_sign\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 48: printf("NRM  '(' exp ')' -> std_nrm\n");
                 xuxa(N->right);
                 break;
        case 49: printf("'!' exp -> exp\n");
                 xuxa(N->right);
                 break;
        case 50: printf("'~' exp -> exp\n");
                 xuxa(N->right);
                 break;
        case 51: printf("exp PPLUS -> exp\n");
                 xuxa(N->left);
                 break;
        case 52: printf("ID PPLUS ';' -> assignment\n");
                 break;
        case 53: printf("exp SHIFTL exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 54: printf("exp SHIFTR exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 55: printf("exp SSHIFTR exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 56: printf("exp '&' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 57: printf("exp '|' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 58: printf("exp '^' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 59: printf("exp LAND exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 60: printf("exp LOR exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 61: printf("exp MOD exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 62: printf("exp '*' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 63: printf("exp '/' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 64: printf("exp '+' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 65: printf("exp '-' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 66: printf("exp '<' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 67: printf("exp '>' exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 68: printf("exp GREQU exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 69: printf("exp LESEQ exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 70: printf("exp EQU exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 71: printf("exp DIF exp -> exp\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 72: printf("USEMAC STRING -> use_macro\n");
                 break;
        case 73: printf("ENDMAC -> end_macro\n");
                 break;
        case 74: printf("ITRADD -> use_inter\n");
                 break;
        case 75: printf("ID '(' exp_list ')' ';' -> void_call\n");
                 break;
        case 76: printf("TYPE ID '=' exp ';' -> declar_full\n");
                 xuxa(N->right);
                 break;
        case 77: printf("TYPE ID '@' exp ';' -> declar_full\n");
                 xuxa(N->right);
                 break;
        case 78: printf("TYPE ID NORM exp ';' -> declar_full\n");
                 xuxa(N->right);
                 break;
        case 79: printf("TYPE ID '$' exp ';' -> declar_full\n");
                 xuxa(N->right);
                 break;
        case 80: printf("TYPE ID EQNE exp ';' -> declar_full\n");
                 xuxa(N->right);
                 break;
        case 81: printf("ID '[' exp ']' '=' exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 82: printf("ID '[' exp ']' '@' exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 83: printf("ID '[' exp ']' NORM exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 84: printf("ID '[' exp ']' '$' exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 85: printf("ID '[' exp ']' EQNE exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 86: printf("ID '[' exp '|' '=' exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 87: printf("ID '[' exp '|' '@' exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 88: printf("ID '[' exp '|' NORM exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 89: printf("ID '[' exp '|' '$' exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 90: printf("ID '[' exp '|' EQNE exp ';' -> assignment\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 91: printf("ID  '[' exp ']' '[' exp ']' '=' exp ';' -> assignment\n");
                 xuxa(N->back);
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 92: printf("WHILE '(' exp ')' -> while_exp\n");
                 xuxa(N->right);
                 break;
        case 93: printf("while_exp stmt_full -> while_stmt\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 94: printf("if_exp stm -> stmt_if\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 95: printf("IF '(' exp ')' -> if_exp\n");
                 xuxa(N->right);
                 break;
        case 96: printf("if_exp stmt_full -> if_exp_stmt\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 97: printf("if_exp_stmt ELSE stmt_full -> ifelse_stmt\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 98: printf("if_exp_stmt ELSE stmt_if -> stmt_if\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
        case 99: printf("while_exp stmt_if -> while_if\n");
                 xuxa(N->left);
                 xuxa(N->right);
                 break;
    }
}
